spring:
  application:
    name: cpwarehouse
  
  data:
    mongodb:
     uri: ${MONGODB_URI:mongodb://cpwarehouse_user:cpwarehouse_pass@localhost:27017/cpwarehouse?authSource=cpwarehouse}

# Logging
logging:
  level:
    io.github.edmaputra.cpwarehouse: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
