spring:
  application:
    name: cpwarehouse
  
  data:
    mongodb:
#      uri: ${MONGODB_URI:mongodb://cpwarehouse_user:cpwarehouse_pass@localhost:27017/cpwarehouse?authSource=cpwarehouse}
      uri: ${MONGODB_URI:mongodb://cpwarehouse_user:cpwarehouse_pass@172.30.217.224:27017/cpwarehouse?authSource=cpwarehouse}
      auto-index-creation: true

# Pagination defaults
application:
  pagination:
    default-page-size: 20
    max-page-size: 100

# Logging
logging:
  level:
    io.github.edmaputra.cpwarehouse: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
